# Generated by Django 5.2.7 on 2025-10-23 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_user_imsi_user_product_id_cents_user_product_id_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for the OCS instance')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('verify_ssl', models.BooleanField(default=False, help_text='Whether to verify SSL certificates')),
                ('accepts_crypto', models.BooleanField(default=False)),
                ('administrators', models.ManyToManyField(blank=True, help_text='Users who have network administrator rights for this instance', related_name='admin_ocs_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCSProductOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Offering name (e.g., 'Data (1G)')", max_length=255)),
                ('offering_id', models.CharField(help_text='ID of the offering in the OCS system', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the offering')),
                ('price', models.FloatField(help_text='Cost for the offering')),
                ('data_mb', models.IntegerField(help_text='Data amount in megabytes')),
                ('validity_days', models.IntegerField(default=30, help_text='How many days the data is valid')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offering is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocs_instance', models.ForeignKey(help_text='The OCS instance this offering belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='product_offerings', to='ocs.ocsinstance')),
            ],
            options={
                'verbose_name': 'OCS Product Offering',
                'verbose_name_plural': 'OCS Product Offerings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bundle name (e.g., '5GB Data Bundle')", max_length=255)),
                ('price', models.FloatField(help_text='Bundle cost')),
                ('payment_method', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('1foryou', '1FourYou'), ('other', 'Other')], help_text='Payment method accepted for this bundle', max_length=20)),
                ('data_mb', models.IntegerField(help_text='Data amount in megabytes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bundle is currently available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocs_instance', models.ForeignKey(help_text='The OCS instance this bundle is for', on_delete=django.db.models.deletion.CASCADE, related_name='data_bundles', to='ocs.ocsinstance')),
                ('product_offering', models.ForeignKey(help_text='The product offering this bundle is based on', on_delete=django.db.models.deletion.CASCADE, related_name='data_bundles', to='ocs.ocsproductoffering')),
            ],
            options={
                'verbose_name': 'Data Bundle',
                'verbose_name_plural': 'Data Bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCSSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(help_text='SIM card IMSI (15 digits)', max_length=15)),
                ('phone_number', models.CharField(help_text='Phone number in international format', max_length=20)),
                ('service_id', models.CharField(help_text='The service ID from OCS API', max_length=255)),
                ('product_id', models.CharField(help_text='The product subscription ID from OCS API', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocs_instance', models.ForeignKey(help_text='The OCS instance this subscriber belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ocs_subscribers', to='ocs.ocsinstance')),
                ('user', models.ForeignKey(help_text='The application user', on_delete=django.db.models.deletion.CASCADE, related_name='ocs_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OCS Subscriber',
                'verbose_name_plural': 'OCS Subscribers',
                'unique_together': {('user', 'ocs_instance')},
            },
        ),
        migrations.CreateModel(
            name='DataPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(help_text='Payment method used', max_length=20)),
                ('amount_paid', models.FloatField(help_text='Amount paid for the bundle')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of purchase')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Status of the purchase', max_length=20)),
                ('bundle', models.ForeignKey(help_text='The bundle that was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ocs.databundle')),
                ('transaction', models.ForeignKey(blank=True, help_text='The blockchain transaction (for crypto payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_purchases', to='core.transaction')),
                ('user', models.ForeignKey(help_text='The user who purchased the bundle', on_delete=django.db.models.deletion.CASCADE, related_name='data_purchases', to=settings.AUTH_USER_MODEL)),
                ('ocs_subscriber', models.ForeignKey(help_text='The OCS subscriber account', on_delete=django.db.models.deletion.CASCADE, related_name='data_purchases', to='ocs.ocssubscriber')),
            ],
            options={
                'verbose_name': 'Data Purchase',
                'verbose_name_plural': 'Data Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
