# Generated by Django 5.2.7 on 2025-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocsinstance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this OCS instance is active and accepting new subscribers'),
        ),
    ]
