# Generated by Django 5.2.7 on 2025-10-24 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0003_alter_ocssubscriber_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocssubscriber',
            unique_together={('user', 'ocs_instance')},
        ),
    ]
