# Generated by Django 5.2.7 on 2025-10-31 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0004_alter_ocssubscriber_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCSMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(max_length=16)),
                ('service_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocs_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocs_mappings', to='ocs.ocsinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocs_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ocs_instance', 'imsi'], name='ocs_ocsmapp_user_id_56ab4a_idx'), models.Index(fields=['product_id'], name='ocs_ocsmapp_product_e5de0b_idx')],
                'unique_together': {('user', 'ocs_instance', 'imsi')},
            },
        ),
    ]
