# Generated by Django 5.2.7 on 2025-10-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0005_ocsmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bytes', models.BigIntegerField(help_text='Amount added in bytes')),
                ('adjustment_id', models.CharField(blank=True, help_text='OCS adjustment ID from the API response', max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', help_text='Status of the top-up', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Description for the top-up', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(help_text='The data bundle that was used for this top-up', on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='ocs.databundle')),
                ('mapping', models.ForeignKey(help_text='The OCS mapping this top-up was applied to', on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='ocs.ocsmapping')),
            ],
            options={
                'verbose_name': 'Top-Up History',
                'verbose_name_plural': 'Top-Up Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mapping', '-created_at'], name='ocs_topuphi_mapping_98759d_idx')],
            },
        ),
    ]
