# Generated by Django 5.1 on 2025-01-23 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusDeskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for the RADIUSdesk instance')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('radius_desk_id', models.IntegerField()),
                ('radius_desk_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clouds', to='radiusdesk.radiusdeskinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('radius_desk_id', models.IntegerField()),
                ('radius_desk_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realms', to='radiusdesk.radiusdeskinstance')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realms', to='radiusdesk.cloud')),
            ],
        ),
        migrations.CreateModel(
            name='RadiusDeskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('radius_desk_id', models.IntegerField()),
                ('data_limit_enabled', models.BooleanField(default=False)),
                ('data_limit_gb', models.FloatField(default=0)),
                ('data_limit_reset', models.CharField(default='never', max_length=255)),
                ('speed_limit_enabled', models.BooleanField(default=False)),
                ('speed_limit_mbs', models.FloatField(default=0)),
                ('limit_session_enabled', models.BooleanField(default=False)),
                ('session_limit', models.IntegerField(default=0)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='radiusdesk.cloud')),
                ('radius_desk_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='radiusdesk.radiusdeskinstance')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='radiusdesk.realm')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='radiusdesk.cloud')),
                ('radius_desk_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='radiusdesk.radiusdeskinstance')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='radiusdesk.realm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
