# Generated by Django 5.1 on 2025-09-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='The specific profile used to create this voucher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='radiusdesk.radiusdeskprofile'),
        ),
    ]
