# Generated by Django 5.1 on 2025-01-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusdeskinstance',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
