# Generated by Django 5.1 on 2025-09-04 11:43

from django.db import migrations


def populate_voucher_profiles(apps, schema_editor):
    """
    Populate the profile field for existing vouchers.
    Since we can't determine the exact profile that was used for existing vouchers,
    we'll use the first profile found in the realm for each voucher.
    """
    Voucher = apps.get_model('radiusdesk', 'Voucher')
    RadiusDeskProfile = apps.get_model('radiusdesk', 'RadiusDeskProfile')
    
    for voucher in Voucher.objects.filter(profile__isnull=True):
        # Find the first profile in the same realm and radius_desk_instance
        profile = RadiusDeskProfile.objects.filter(
            realm=voucher.realm,
            radius_desk_instance=voucher.radius_desk_instance
        ).first()
        
        if profile:
            voucher.profile = profile
            voucher.save()


def reverse_populate_voucher_profiles(apps, schema_editor):
    """
    Reverse migration - set profile to None for all vouchers.
    """
    Voucher = apps.get_model('radiusdesk', 'Voucher')
    Voucher.objects.update(profile=None)


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0002_voucher_profile'),
    ]

    operations = [
        migrations.RunPython(
            populate_voucher_profiles,
            reverse_populate_voucher_profiles
        ),
    ]
