# Generated by Django 5.1 on 2025-01-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0002_alter_radiusdeskinstance_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realm',
            old_name='realm',
            new_name='cloud',
        ),
    ]
