# Generated by Django 5.1 on 2025-03-19 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0004_voucher_wallet_address_alter_voucher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusdeskinstance',
            name='administrators',
            field=models.ManyToManyField(blank=True, help_text='Users who have network administrator rights for this instance', related_name='admin_radiusdesk_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
