# Generated by Django 5.1 on 2025-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0005_radiusdeskinstance_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusdeskinstance',
            name='accepts_crypto',
            field=models.BooleanField(default=False),
        ),
    ]
