# Generated by Django 5.2.7 on 2025-10-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0005_internetbundle_bundlepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetbundle',
            name='payment_method',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('1foryou', '1FourYou'), ('other', 'Other')], help_text='Payment method accepted for this bundle', max_length=20),
        ),
    ]
