# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0006_alter_internetbundle_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusdeskprofile',
            name='payment_method',
            field=models.CharField(
                choices=[('crypto', 'Cryptocurrency'), ('1foryou', '1FourYou'), ('other', 'Other')],
                default='crypto',
                help_text='Payment method accepted for this profile',
                max_length=20
            ),
        ),
    ]




