# Generated by Django 5.1 on 2025-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiusdesk', '0006_radiusdeskinstance_accepts_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusdeskprofile',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
