# Generated by Django 5.1 on 2025-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_create_continuous_aggregates_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='device_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('dns_server', 'DNS Server'), ('server', 'Server'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('switch', 'Switch')], default='unknown', help_text='Select the type of device (DNS Server, Server, Firewall, Access Point, Switch)', max_length=20),
        ),
    ]
