# Generated by Django 5.1 on 2025-03-21 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_network_host_network_ping_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address in format XX:XX:XX:XX:XX:XX.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('network', 'ip_address'), ('network', 'mac_address')},
        ),
    ]
