# Generated by Django 5.1 on 2025-03-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_network_name_alter_network_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('network', 'ip_address')},
        ),
    ]
