# Generated by Django 5.1 on 2024-10-04 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('token_common_name', models.CharField(default='KRONE', max_length=255)),
                ('token', models.CharField(default='KRONE', max_length=255)),
                ('token_type', models.CharField(default='ERC-20', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
