# Generated by Django 5.1 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_imsi_user_product_id_cents_user_product_id_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='oneforyou_reference',
            field=models.CharField(blank=True, help_text='1FourYou transaction reference for querying', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='change_voucher_pin',
            field=models.CharField(blank=True, help_text='Change voucher PIN if partial redemption', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='change_voucher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change voucher amount in ZAR', max_digits=18, null=True),
        ),
    ]





