# Generated by Django 5.1 on 2024-10-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smartcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsIndexContract',
            fields=[
                ('smartcontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.smartcontract')),
                ('owner_address', models.CharField(max_length=255)),
                ('entry', models.BooleanField(default=False)),
                ('entry_count', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=False)),
                ('deactivate', models.BooleanField(default=False)),
                ('add', models.BooleanField(default=False)),
                ('remove', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account Index Smart Contract',
                'verbose_name_plural': 'Account Index Smart Contracts',
            },
            bases=('core.smartcontract',),
        ),
        migrations.CreateModel(
            name='FaucetSmartContract',
            fields=[
                ('smartcontract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.smartcontract')),
                ('gimme', models.BooleanField(default=False)),
                ('give_to', models.BooleanField(default=False)),
                ('next_balance', models.BooleanField(default=False)),
                ('next_time', models.BooleanField(default=False)),
                ('registry_address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Faucet Smart Contract',
                'verbose_name_plural': 'Faucet Smart Contracts',
            },
            bases=('core.smartcontract',),
        ),
        migrations.AlterModelOptions(
            name='smartcontract',
            options={'verbose_name': 'Smart Contract', 'verbose_name_plural': 'Smart Contracts'},
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='contract_type',
            field=models.CharField(max_length=255),
        ),
    ]
