# Generated by Django 5.1 on 2024-10-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accountsindexcontract_faucetsmartcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucetsmartcontract',
            name='owner_address',
            field=models.CharField(default='0xB821E49ADB53F0AbeD834278d5dFc57901c30Eea', max_length=255),
            preserve_default=False,
        ),
    ]
