# Generated by Django 5.1 on 2024-12-05 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_hash', models.CharField(max_length=256)),
                ('block_number', models.IntegerField()),
                ('gas_used', models.DecimalField(decimal_places=8, max_digits=18)),
                ('category', models.CharField(choices=[('TRANSFER', 'Transfer'), ('REWARD', 'Reward'), ('PAYMENT', 'Payment'), ('OTHER', 'Other')], default='TRANSFER', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_transactions', 'Can view all transactions')],
            },
        ),
    ]
