# Generated by Django 5.1 on 2024-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AddField(
            model_name='transaction',
            name='block_hash',
            field=models.CharField(default='0x00', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block_number',
            field=models.CharField(max_length=256),
        ),
    ]
