# Generated by Django 5.1 on 2025-03-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_sender_address_transaction_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('network_admin', 'Can administer the network'),)},
        ),
    ]
