# Generated by Django 5.1 on 2025-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
