# Generated by Django 5.1 on 2025-02-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_transaction_sender_address_transaction_token_and_more'),
        ('network', '0005_host_device_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reward Name', max_length=255)),
                ('reward_type', models.CharField(choices=[('uptime', 'Uptime Based'), ('custom', 'Custom')], default='uptime', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('once_off', models.BooleanField(default=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='network.host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UptimeRewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime_seconds', models.IntegerField(help_text='Total uptime in seconds')),
                ('percentage_awarded', models.DecimalField(decimal_places=2, help_text='Percentage of total reward', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transaction', to='reward.reward')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transaction', to='core.transaction')),
            ],
        ),
    ]
