# Generated by Django 5.1 on 2025-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='interval_minutes',
            field=models.IntegerField(blank=True, help_text='Interval for recurring rewards in minutes', null=True),
        ),
    ]
