# Generated by Django 5.1 on 2025-02-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_reward_interval_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimerewardtransaction',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to='reward.reward'),
        ),
    ]
