# Generated by Django 5.1 on 2025-03-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_network_host_network_ping_network'),
        ('reward', '0003_alter_uptimerewardtransaction_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='network',
            field=models.ForeignKey(blank=True, help_text='Network associated with this reward', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='network.network'),
        ),
    ]
